import React, { useEffect } from 'react'
import Breadcrumbs from '../../../../../Components/Breadcrumbs/Breadcrumbs'
import { Col, Row } from 'react-bootstrap';
import '../StockIn.css';
import { useDispatch, useSelector } from 'react-redux';
import { stockInRequests } from '../../../../../Redux/Action/Admin';
import Loader from '../../../../../Util/Loader';
import { useNavigate } from 'react-router-dom';

const StockInRequests = () => {
    const dispatch = useDispatch();
    const navigate = useNavigate();

    const { loading, getStockInRequestData } = useSelector((state) => state.stockInRequestsData)

    useEffect(() => {
        dispatch(stockInRequests())
    }, [])

    return (
        <div>
            <Breadcrumbs list={["Dashboard", "Stock In Requests"]} />

            <div className='material_main'>
                <h5> Stock In Requests</h5>

                <div className='stockin_request_main'>
                    {
                        loading ? <Loader /> :
                            <Row style={{ gap: "15px 0" }}>
                                {
                                    getStockInRequestData?.response?.map((s) => {
                                        return (
                                            <Col md={6}>
                                                <div className='stockin_request_box'>
                                                    <p> <span>Warehouse: </span> {s.warehouse} </p>
                                                    <p> <span>Request Number: </span> {s.requestNumber} </p>
                                                    <p> <span>Generated By: </span> {s.generatedBy} </p>
                                                    <p> <span>Date: </span> {s.date} </p>
                                                    <button onClick={() => navigate(`/wms/stockin-requests/detail/${s.id}`, { state: { indData: s } })}>Details</button>
                                                </div>
                                            </Col>
                                        )
                                    })
                                }
                            </Row>
                    }
                </div>
            </div>
        </div>
    )
}

export default StockInRequests